### ISSUE TITLE
Refresh data

### ISSUE THREAD

**Issue by ismailkoksal** [angelnikolov/ts-cacheable#110]
Hello, when I'm adding a new item, it don't refresh data

```ts
const cacheBuster$ = new Subject<void>();

@Injectable({
  providedIn: 'root',
})
export class CollectsScheduleService {
  constructor(private http: HttpClient) {}

  @Cacheable({
    cacheBusterObserver: cacheBuster$,
  })
  getAll(crematoriumId: number): Observable<CollectSchedule[]> {
    return this.http.get<CollectSchedule[]>(
      `/collect-schedule/crematorium/${crematoriumId}`
    );
  }

  @CacheBuster({
    cacheBusterNotifier: cacheBuster$,
  })
  add(day: Day, zoneId: number): Observable<CollectSchedule> {
    return this.http.post<CollectSchedule>('/collect-schedule', {
      day,
      zoneId,
    });
  }
}

```

**Comment by ismailkoksal** [comment]
nvm, I thought it automatically refresh. I need to it manually

**Comment by ismailkoksal** [comment]
I don't know how refresh data, it still doesn't work

**Comment by angelnikolov** [comment]
@ismailkoksal The cache will be cleared once the Observable returned from the method you've decorated with CacheBuster() has emitted.
The issue here is that the CacheBuster also works with `tap()` as you can see here https://github.com/angelnikolov/ts-cacheable/blob/master/cache-buster.decorator.ts#L17.
Basically, in your case, your `tap()` call will be executed before the CacheBuster one, because that was added to the Observable chain at a later stage. Therefore, you will still use the cache.

**Comment by ismailkoksal** [comment]
I also tried this

```ts
this.collectsScheduleService.add().subscribe(() =>
    this.collectsScheduleService.getAll().subscribe()
);
```

Still don't work

**Comment by ismailkoksal** [comment]
Can you provide an example to my code on how to refresh after adding an item please

**Comment by ismailkoksal** [comment]
This is working

```ts
export const cacheBuster$ = new BehaviorSubject(undefined);
```

```ts
constructor(private collectsScheduleService: CollectsScheduleService) {
    this.collects$ = cacheBuster$.pipe(switchMap(() => collectsScheduleService.getAll()));
  }
```

**Comment by angelnikolov** [comment]
@ismailkoksal Can you check this example?
https://stackblitz.com/edit/ngx-cacheable-my31me?file=src%2Fapp%2Fapp.component.ts
We have a get/update/get and it all works. It uses the latest version of `ts-cacheable`.
